name: Build Pipeline for the Prime Generator Project

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build the project with Maven (compile, test, and package the JAR)
      - name: Build with Maven
        run: mvn clean package --batch-mode --update-snapshots

      # Upload the JAR and other Assets (MD5, SHA1)
      - name: Upload JAR to GitHub Packages
        run: |
          JAR_PATH="target/prime-generator-1.0-SNAPSHOT.jar"
          POM_PATH="pom.xml"
          VERSION="${{ github.event.release.tag_name }}"

          # Deploy JAR file to GitHub Packages
          mvn deploy:deploy-file \
            -Dfile=${JAR_PATH} \
            -DpomFile=${POM_PATH} \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/${{ github.repository_owner }}/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=${VERSION} \
            -Dpackaging=jar

          # Deploy MD5 checksum
          mvn deploy:deploy-file \
            -Dfile=${JAR_PATH}.md5 \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/${{ github.repository_owner }}/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=${VERSION} \
            -Dpackaging=md5

          # Deploy SHA1 checksum
          mvn deploy:deploy-file \
            -Dfile=${JAR_PATH}.sha1 \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/${{ github.repository_owner }}/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=${VERSION} \
            -Dpackaging=sha1