name: Deploy JAR to GitHub Packages on Release

on:
  release:
    types: [created]  # Trigger when a new release is create

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build the project with Maven (compile, test, and package the JAR)
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
       
      - name: Build with Maven
        run: mvn --batch-mode deploy

      