name: Build and Deploy to GitHub Packages

on:
  push:
    branches:
      - main  # or any branch you're working with

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build the project with Maven (compile, test, and package the JAR)
      - name: Build with Maven
        run: mvn clean package --batch-mode --update-snapshots

      # Set the version based on the commit hash
      - name: Set Version (using commit hash)
        id: set_version
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "Version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Sets the version as an environment variable

      