name: Build Pipeline for the Prime Generator Project Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Debug Environment Variables
        run: |
          echo "GITHUB_ACTOR=${{ github.actor }}"
          echo "GITHUB_TOKEN is set? ${{ secrets.GITHUB_TOKEN != '' }}"
          echo "VERSION=${{ env.VERSION }}"
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup Maven
        run: sudo apt-get install maven -y
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package 

      # Upload the JAR to GitHub Packages
      - name: Deploy to GitHub Packages
        run: |
          mvn deploy:deploy-file \
            -Dfile=target/prime-generator-1.0-SNAPSHOT.jar \
            -DpomFile=pom.xml \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/Sebronio/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=1.0-SNAPSHOT \
            -Dpackaging=jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}