name: Build Pipeline for the Prime Generator Project

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build the project
      - name: Build with Maven
        run: 
          mvn clean package --batch-mode --update-snapshots package

      # Upload the Jar and other Assets
      - name: Upload JAR to GitHub Packages
        run:
          JAR_PATH="target/prime-generator-1.0-SNAPSHOT.jar"
          POM_PATH="pom.xml"
          VERSION="${{ github.event.release.tag_name }}"

          mvn deploy:deploy-file \
          -Dfile=${JAR_PATH} \
            -DpomFile=${POM_PATH} \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/${{ github.repository_owner }}/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=${VERSION} \
            -Dpackaging=jar

          mvn deploy:deploy-file \
            -Dfile=${JAR_PATH}.md5 \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/${{ github.repository_owner }}/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=${VERSION} \
            -Dpackaging=md5

          mvn deploy:deploy-file \
            -Dfile=${JAR_PATH}.sha1 \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/${{ github.repository_owner }}/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=${VERSION} \
            -Dpackaging=sha1
                  
     