name: Build and Deploy to GitHub Packages

on:
  push:
    branches:
      - main  # or any branch you're working with

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build the project with Maven (compile, test, and package the JAR)
      - name: Build with Maven
        run: mvn clean package --batch-mode --update-snapshots

      # Set the version based on the commit hash
      - name: Set Version (using commit hash)
        id: set_version
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "Version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Sets the version as an environment variable

      # Upload the JAR and other Assets (MD5, SHA1)
      - name: Upload JAR to GitHub Packages
        run: |
          JAR_PATH="target/prime-generator-1.0-SNAPSHOT.jar"
          POM_PATH="pom.xml"
          
          # Use the dynamically set version from the previous step
          VERSION=${{ env.VERSION }}
          echo "Using version: $VERSION"

          # Deploy JAR file to GitHub Packages
          mvn deploy:deploy-file \
            -Dfile=${JAR_PATH} \
            -DpomFile=${POM_PATH} \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/Sebronio/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=${VERSION} \
            -Dpackaging=jar

          # Deploy MD5 checksum
          mvn deploy:deploy-file \
            -Dfile=${JAR_PATH}.md5 \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/Sebronio/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=${VERSION} \
            -Dpackaging=md5

          # Deploy SHA1 checksum
          mvn deploy:deploy-file \
            -Dfile=${JAR_PATH}.sha1 \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/Sebronio/prime-generator \
            -DgroupId=uk.ac.open.primegenerator \
            -DartifactId=prime-generator \
            -Dversion=${VERSION} \
            -Dpackaging=sha1