name: Deploy JAR to GitHub Packages on Release

on:
  release:
    types: [created]  # Trigger when a new release is create

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Build the project with Maven (compile, test, and package the JAR)
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      # Set up Maven settings with your Personal Access Token
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
                      xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
                      xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0
                                          http://maven.apache.org/xsd/settings-1.0.0.xsd\">
          <servers>
            <server>
              <id>github</id>
              <username>Sebronio</username>
              <password>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</password>
            </server>
          </servers>
          </settings>" > ~/.m2/settings.xml
        
      - name: Build with Maven
        run: mvn --batch-mode deploy

      